### ISSUE TITLE
Create main layout component

### ISSUE THREAD

**Issue by wcf-mstacey** [WCF-Insurance/WCF-Cashmere#43]
We would like to have a main layout component created. This would be a component that gives us the side nav, top progress (if needed), a card or tile for the main content of the page.

We would like to have the progress spinner be part of this component so we can turn it off or on, but it will come up in a consistent location in all of our apps.

We would also like to have pieces of this layout "sticky". For instance, the sidenav we want to stay put as the user scrolls down on the main content of the page. Same with the summary section.

**Comment by c0d3r1010** [comment]
@wcf-mstacey, @tfoxley, @tommybay Are there any Zeplin Mockups for what the full layout looks like? I am working on #91 and am wanting to make sure I keep this story (#43) in mind. It will also be helpful to have mockup for this when I finish with #91.

**Comment by tommybay** [comment]
Sorry, @c0d3r1010  - I totally missed this. Let me throw some stuff in Zeplin and then we can chat through it. I'm honestly not sure how truly "thought out" this component is. Haha

**Comment by tommybay** [comment]
@c0d3r1010 - sorry for the delay. As I started going through it, we decided to make a slight change. Instead of a _single_ main layout component, we want to create **two** of them. A 'simple layout' and a 'complex layout'. 

The simple layout is for apps that don't need any navigation (the app has a single purpose or function). It will include a header component, a body component, a footer component (that can be turned off), and the spinner component. An example of this layout would be the Pay Invoice app (in Zeplin).

The complex layout is for apps that need navigation. It will include the side-nav component, a body component, and the spinner component. An example of this layout would be the OLIV app (in Zeplin).

We may end up including additional sub components into these main layout components, but we'll start with these lists for now.

Does that make sense? What questions do you have?

**Comment by c0d3r1010** [comment]
That seems to make sense. Thank you!

**Comment by c0d3r1010** [comment]
Hey @tommybay I am going to start on this story today!

**Comment by tfoxley** [comment]
We determined that this is not feasible.
